Configure evaluation version of 'prm4j'

diff --git a/prm4j b/prm4j
--- a/prm4j
+++ b/prm4j
@@ -1,14 +1,9 @@
 #!/usr/bin/env bash
 
-# Compiles and runs JavaMOP aspects with the DaCapo-9.12-bach benchmark using aspectj load-time weaving.
+# Compiles and runs prm4j aspects with the DaCapo-9.12-bach benchmark using aspectj load-time weaving.
 
-# usage:         ./prm4j <monitored property> <benchmark>
+# usage:         ./prm4j
 
-# example usage: ./prm4j SafeMapIterator avrora
-#                ./prm4j SafeMapIterator "h2 --converge"
-#                ./prm4j SafeIterator eclipse
-
-# list of all monitored properties can be found in target/jars/prm4j; each jar is property
 # list of all benchmarks can be found at http://dacapobench.org/benchmarks.html 
 
 # remember directory where this script is called
@@ -39,35 +34,41 @@ mkdir -p target/classes/META-INF target/jars/prm4j
 
 # compile the aspect into classes
 echo "Compiling aspect..."
-java -jar $AJC -cp $GUAVA:$PRM4J:$RT:$DACAPO src/main/java/prm4j/* -d target/classes -6
-
-# create custom aop-ajc.xml and put in META-INF
-sed 's/<aspectname>/prm4j.'$1'/g' src/main/resources/prm4j/aop-ajc.xml > target/classes/META-INF/aop-ajc.xml
-
-# repackage each aspect into a single jars with the custom aop-ajc.xml
-jar cf target/jars/prm4j/$1.jar -C target/classes META-INF/aop-ajc.xml -C target/classes prm4j/$1.class -C target/classes prm4j/FSM_$1.class
+java -jar $AJC -cp $GUAVA:$PRM4J:$RT:$DACAPO:$APACHEMATH src/main/java/prm4j/* -d target/classes -6
 
 # create jar with callback
-javac src/main/java/prm4jeval/* -d target/classes -cp $DACAPO:$APACHEMATH:$GUAVA
+javac src/main/java/prm4jeval/*.java -d target/classes -cp $DACAPO:$APACHEMATH:$GUAVA
 jar cf target/jars/Callback.jar -C target/classes .
 
-# cleanup custom aop-ajc.xml
-rm target/classes/META-INF/aop-ajc.xml
-
 # load-time weaving via aspectjweaver
-for benchmark in avrora h2; do
-	for i in {1..15}; do
-	STATUS=0
-		while [ $STATUS -eq 0 ]; do
-    		echo "Starting benchmark [prm4j:$benchmark:$2] measurement $i..."
-			java -Xms256M -Xmx1024M -javaagent:${WEAVER} -Xbootclasspath/a:$RT \
-				-Dprm4jeval.outputfile=results/prm4j.ser \
-				-Dprm4jeval.benchmark=$benchmark -Dprm4jeval.parametricProperty=$1 \
-				-cp $DACAPO:$GUAVA:$PRM4J:$APACHEMATH:${DIR}/target/jars/prm4j/$1.jar:${DIR}/target/jars/Callback.jar \
-				Harness -c prm4jeval.EvalCallback $benchmark
-			STATUS=$?
+for invocation in {0..15}; do
+	for paramProperty in HasNext SafeIterator SafeMapIterator SafeSyncCollection SafeSyncMap ; do
+		
+		# create custom aop-ajc.xml and put in META-INF
+		sed 's/<aspectname>/prm4j.'$paramProperty'/g' src/main/resources/prm4j/aop-ajc.xml > target/classes/META-INF/aop-ajc.xml
+
+		# repackage each aspect into a single jars with the custom aop-ajc.xml
+		jar cf target/jars/prm4j/${paramProperty}.jar -C target/classes META-INF/aop-ajc.xml -C target/classes prm4j/${paramProperty}.class -C target/classes prm4j/FSM_${paramProperty}.class
+
+		# cleanup custom aop-ajc.xml
+		rm target/classes/META-INF/aop-ajc.xml
+		
+		for benchmark in avrora batik eclipse fop h2 jython luindex \
+					pmd sunflow tomcat tradebeans tradesoap xalan ; do
+		STATUS=0
+			while [ $STATUS -eq 0 ]; do
+    			echo "Starting benchmark [prm4j:$benchmark:$paramProperty] measurement $invocation..."
+				java -Xms256M -Xmx2048M -javaagent:${WEAVER} -Xbootclasspath/a:$RT \
+					-Dprm4jeval.invocation=$invocation \
+					-Dprm4j.debug=true \
+					-Dprm4j.monitorCleaningInterval=500 \
+					-Dprm4j.experimentName="${invocation} ${benchmark} ${paramProperty}" \
+					-Dprm4jeval.outputfile=logs/prm4j.log \
+					-Dprm4jeval.benchmark=${benchmark} -Dprm4jeval.parametricProperty=${paramProperty} \
+					-cp $DACAPO:$GUAVA:$PRM4J:$APACHEMATH:${DIR}/target/jars/prm4j/${paramProperty}.jar:${DIR}/target/jars/Callback.jar \
+					Harness --no-validation -c prm4jeval.EvalCallback $benchmark
+				STATUS=$?
+			done
 		done
 	done
-done 
-
-
+done
